// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuantityMeasurementModel.Context;

#nullable disable

namespace QuantityMeasurementRepository.Migrations
{
    [DbContext(typeof(QuantityMeasurementDbContext))]
    [Migration("20260406155153_AddUserIdToMeasurements")]
    partial class AddUserIdToMeasurements
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuantityMeasurementModel.Entities.QuantityMeasurement", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("id");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("ErrorDetails").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("error_details");
                    b.Property<string>("FirstOperandCategory").HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("first_operand_category");
                    b.Property<string>("FirstOperandDisplay").HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("first_operand_display");
                    b.Property<string>("FirstOperandUnit").HasMaxLength(30).HasColumnType("character varying(30)").HasColumnName("first_operand_unit");
                    b.Property<double?>("FirstOperandValue").HasColumnType("double precision").HasColumnName("first_operand_value");
                    b.Property<string>("FormattedResult").HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("formatted_result");
                    b.Property<bool>("IsSuccessful").HasColumnType("boolean").HasColumnName("is_successful");
                    b.Property<string>("OperationType").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("operation_type");
                    b.Property<string>("ResultMeasurementType").HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("result_measurement_type");
                    b.Property<string>("ResultUnit").HasMaxLength(30).HasColumnType("character varying(30)").HasColumnName("result_unit");
                    b.Property<double?>("ResultValue").HasColumnType("double precision").HasColumnName("result_value");
                    b.Property<string>("SecondOperandCategory").HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("second_operand_category");
                    b.Property<string>("SecondOperandDisplay").HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("second_operand_display");
                    b.Property<string>("SecondOperandUnit").HasMaxLength(30).HasColumnType("character varying(30)").HasColumnName("second_operand_unit");
                    b.Property<double?>("SecondOperandValue").HasColumnType("double precision").HasColumnName("second_operand_value");
                    b.Property<string>("TargetUnit").HasMaxLength(30).HasColumnType("character varying(30)").HasColumnName("target_unit");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.Property<long?>("UserId").HasColumnType("bigint").HasColumnName("user_id");
                    b.HasKey("Id");
                    b.HasIndex("CreatedAt").HasDatabaseName("idx_created_at");
                    b.HasIndex("FirstOperandCategory").HasDatabaseName("idx_measurement_type");
                    b.HasIndex("IsSuccessful").HasDatabaseName("idx_is_successful");
                    b.HasIndex("OperationType").HasDatabaseName("idx_operation_type");
                    b.HasIndex("UserId").HasDatabaseName("idx_user_id");
                    b.ToTable("quantity_measurements", (string)null);
                });

            modelBuilder.Entity("QuantityMeasurementModel.Entities.User", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint").HasColumnName("id");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("email");
                    b.Property<string>("FullName").HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("full_name");
                    b.Property<string>("GoogleId").HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("google_id");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("text").HasColumnName("password_hash");
                    b.Property<string>("PictureUrl").HasMaxLength(1000).HasColumnType("character varying(1000)").HasColumnName("picture_url");
                    b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("role");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("username");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique().HasDatabaseName("idx_users_email");
                    b.HasIndex("Username").IsUnique().HasDatabaseName("idx_users_username");
                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}